FROM bridge_nix-base

# https://iohk.zendesk.com/hc/en-us/articles/900000672303-How-to-build-and-run-cardano-wallet-using-Nix
RUN git clone https://github.com/input-output-hk/cardano-node.git
RUN cd cardano-node && \
    nix-build --show-trace -A scripts.testnet.node -o testnet-node-local

# Command for running cardano-node:
#
#   cd cardano-node && ./testnet-node-local/bin/cardano-node-testnet
